const currencies = {
  USD: { code: "USD", symbol: "$", name: "United States Dollar" },
  EUR: { code: "EUR", symbol: "€", name: "Euro" },
  PKR: { code: "PKR", symbol: "£", name: "Euro" },
  GBP: { code: "GBP", symbol: "£", name: "British Pound Sterling" },
  JPY: { code: "JPY", symbol: "¥", name: "Japanese Yen" },
  AUD: { code: "AUD", symbol: "A$", name: "Australian Dollar" },
  CAD: { code: "CAD", symbol: "C$", name: "Canadian Dollar" },
  CHF: { code: "CHF", symbol: "CHF", name: "Swiss Franc" },
  CNY: { code: "CNY", symbol: "¥", name: "Chinese Yuan" },
  HKD: { code: "HKD", symbol: "HK$", name: "Hong Kong Dollar" },
  NZD: { code: "NZD", symbol: "NZ$", name: "New Zealand Dollar" },
  SEK: { code: "SEK", symbol: "kr", name: "Swedish Krona" },
  KRW: { code: "KRW", symbol: "₩", name: "South Korean Won" },
  SGD: { code: "SGD", symbol: "S$", name: "Singapore Dollar" },
  NOK: { code: "NOK", symbol: "kr", name: "Norwegian Krone" },
  MXN: { code: "MXN", symbol: "Mex$", name: "Mexican Peso" },
  INR: { code: "INR", symbol: "₹", name: "Indian Rupee" },
  BRL: { code: "BRL", symbol: "R$", name: "Brazilian Real" },
  RUB: { code: "RUB", symbol: "₽", name: "Russian Ruble" },
  ZAR: { code: "ZAR", symbol: "R", name: "South African Rand" },
  TRY: { code: "TRY", symbol: "₺", name: "Turkish Lira" },
  AED: { code: "AED", symbol: "د.إ", name: "United Arab Emirates Dirham" },
  SAR: { code: "SAR", symbol: "﷼", name: "Saudi Riyal" },
  IDR: { code: "IDR", symbol: "Rp", name: "Indonesian Rupiah" },
  PHP: { code: "PHP", symbol: "₱", name: "Philippine Peso" },
  THB: { code: "THB", symbol: "฿", name: "Thai Baht" },
  MYR: { code: "MYR", symbol: "RM", name: "Malaysian Ringgit" },
  PLN: { code: "PLN", symbol: "zł", name: "Polish Złoty" },
};

export default currencies;
